# Perfil de testes: H2 em memória e mock do REST Client
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

twitch.client-id=test-client-id
twitch.client-secret=test-client-secret
twitch.auth-url=http://localhost:8083
